<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rrbot">

  <xacro:include filename="$(find rrbot_description)/urdf/rrbot_properties.xacro"/>
  <xacro:include filename="$(find rrbot_description)/urdf/macros.xacro"/>
  <xacro:include filename="$(find rrbot_description)/urdf/materials.xacro"/>
  <xacro:include filename="$(find rrbot_description)/urdf/gazebo_properties.xacro"/>
  <xacro:include filename="$(find rrbot_description)/urdf/gazebo_plugins.xacro"/>

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="link1"/>
  </joint>

  <!-- Base Link -->
  <link name="link1">
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height1}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <xacro:box_inertia mass="${mass}" width="${width}" height="${height1}" />
    </inertial>
   
  </link>

  <joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="${camera_link} 0 ${height3 - axel_offset*2}" rpy="0 0 0"/>
    <parent link="link1"/>
    <child link="camera_link"/>
  </joint>

  <!-- Camera -->
  <link name="camera_link">
    <collision>
      <origin xyz="0 0 ${height2}" rpy="0 -0.95 0"/>
      <geometry>
	<cylinder radius="${camera_link}" length="${camera_link*2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height2}" rpy="0 -0.95 0"/>
      <geometry>
	<cylinder radius="${camera_link}" length="${camera_link*2}"/>
      </geometry>
      <material name="grey"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 ${height2}" rpy="0 0.5 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

</robot>
